# Part 1
<p>They need you to find the two entries that sum to 2020 and then multiply those two numbers together.</p>

In [1]:
f = open('input.txt','r')
print(f.read())

408
1614
1321
1028
1018
2008
1061
1433
1434
1383
1645
1841
1594
1218
1729
1908
1237
1152
1771
1837
1709
1449
1876
1763
1676
1491
1983
1743
1845
999
1478
1929
1819
1385
1308
1703
1246
1831
1964
1469
1977
1488
1698
1640
1513
1136
1794
1685
1802
1520
1807
1654
1547
1917
1792
1949
1268
1626
1493
1534
1700
1844
1146
1049
1811
1627
1630
1755
1887
1290
1446
1968
168
1749
1479
1651
1646
1839
14
1918
1568
1554
1926
1942
1862
1966
1536
1599
1439
1766
1643
1045
1537
1786
1596
1954
1390
1981
1362
1292
1573
1541
1515
1567
1860
1066
1879
1800
1309
1533
1812
1774
1119
1602
1677
482
1054
1424
1631
1829
1550
1636
1604
185
1642
1304
1843
1773
1667
1530
1047
1584
1958
1160
1570
1705
1582
1692
1886
1673
1842
1402
1517
1805
1386
1165
1867
1153
1467
1473
1803
1967
1485
1448
1922
1258
1590
1996
1208
1241
1412
1610
1219
523
1813
1123
1916
1861
1020
1783
1052
1140
1994
1761
747
1885
1675
1957
1476
1382
1878
1099
1882
855
1905
1037
1714
1988
1648
1135
1859
1798
1333
1158
1909
652
1934
1830
1442
1224

In [47]:
#read the input and put it in a list
text_file = open("input.txt", "r")
lines = text_file.readlines()
print (lines)
print (len(lines))
text_file.close()

['408\n', '1614\n', '1321\n', '1028\n', '1018\n', '2008\n', '1061\n', '1433\n', '1434\n', '1383\n', '1645\n', '1841\n', '1594\n', '1218\n', '1729\n', '1908\n', '1237\n', '1152\n', '1771\n', '1837\n', '1709\n', '1449\n', '1876\n', '1763\n', '1676\n', '1491\n', '1983\n', '1743\n', '1845\n', '999\n', '1478\n', '1929\n', '1819\n', '1385\n', '1308\n', '1703\n', '1246\n', '1831\n', '1964\n', '1469\n', '1977\n', '1488\n', '1698\n', '1640\n', '1513\n', '1136\n', '1794\n', '1685\n', '1802\n', '1520\n', '1807\n', '1654\n', '1547\n', '1917\n', '1792\n', '1949\n', '1268\n', '1626\n', '1493\n', '1534\n', '1700\n', '1844\n', '1146\n', '1049\n', '1811\n', '1627\n', '1630\n', '1755\n', '1887\n', '1290\n', '1446\n', '1968\n', '168\n', '1749\n', '1479\n', '1651\n', '1646\n', '1839\n', '14\n', '1918\n', '1568\n', '1554\n', '1926\n', '1942\n', '1862\n', '1966\n', '1536\n', '1599\n', '1439\n', '1766\n', '1643\n', '1045\n', '1537\n', '1786\n', '1596\n', '1954\n', '1390\n', '1981\n', '1362\n', '1292\n', '1573\n', '1541\n', '1515\n', '1567\n', '1860\n', '1066\n', '1879\n', '1800\n', '1309\n', '1533\n', '1812\n', '1774\n', '1119\n', '1602\n', '1677\n', '482\n', '1054\n', '1424\n', '1631\n', '1829\n', '1550\n', '1636\n', '1604\n', '185\n', '1642\n', '1304\n', '1843\n', '1773\n', '1667\n', '1530\n', '1047\n', '1584\n', '1958\n', '1160\n', '1570\n', '1705\n', '1582\n', '1692\n', '1886\n', '1673\n', '1842\n', '1402\n', '1517\n', '1805\n', '1386\n', '1165\n', '1867\n', '1153\n', '1467\n', '1473\n', '1803\n', '1967\n', '1485\n', '1448\n', '1922\n', '1258\n', '1590\n', '1996\n', '1208\n', '1241\n', '1412\n', '1610\n', '1219\n', '523\n', '1813\n', '1123\n', '1916\n', '1861\n', '1020\n', '1783\n', '1052\n', '1140\n', '1994\n', '1761\n', '747\n', '1885\n', '1675\n', '1957\n', '1476\n', '1382\n', '1878\n', '1099\n', '1882\n', '855\n', '1905\n', '1037\n', '1714\n', '1988\n', '1648\n', '1135\n', '1859\n', '1798\n', '1333\n', '1158\n', '1909\n', '652\n', '1934\n', '1830\n', '1442\n', '1224']
200

In [48]:
#convert from string to int
for i in range(0, len(lines)): 
    lines[i] = int(lines[i])

In [53]:
#copy to do add each
temp = lines.copy()
print(lines)

[408, 1614, 1321, 1028, 1018, 2008, 1061, 1433, 1434, 1383, 1645, 1841, 1594, 1218, 1729, 1908, 1237, 1152, 1771, 1837, 1709, 1449, 1876, 1763, 1676, 1491, 1983, 1743, 1845, 999, 1478, 1929, 1819, 1385, 1308, 1703, 1246, 1831, 1964, 1469, 1977, 1488, 1698, 1640, 1513, 1136, 1794, 1685, 1802, 1520, 1807, 1654, 1547, 1917, 1792, 1949, 1268, 1626, 1493, 1534, 1700, 1844, 1146, 1049, 1811, 1627, 1630, 1755, 1887, 1290, 1446, 1968, 168, 1749, 1479, 1651, 1646, 1839, 14, 1918, 1568, 1554, 1926, 1942, 1862, 1966, 1536, 1599, 1439, 1766, 1643, 1045, 1537, 1786, 1596, 1954, 1390, 1981, 1362, 1292, 1573, 1541, 1515, 1567, 1860, 1066, 1879, 1800, 1309, 1533, 1812, 1774, 1119, 1602, 1677, 482, 1054, 1424, 1631, 1829, 1550, 1636, 1604, 185, 1642, 1304, 1843, 1773, 1667, 1530, 1047, 1584, 1958, 1160, 1570, 1705, 1582, 1692, 1886, 1673, 1842, 1402, 1517, 1805, 1386, 1165, 1867, 1153, 1467, 1473, 1803, 1967, 1485, 1448, 1922, 1258, 1590, 1996, 1208, 1241, 1412, 1610, 1219, 523, 1813, 1123, 1916, 1861, 1020, 1783, 1052, 1140, 1994, 1761, 747, 1885, 1675, 1957, 1476, 1382, 1878, 1099, 1882, 855, 1905, 1037, 1714, 1988, 1648, 1135, 1859, 1798, 1333, 1158, 1909, 652, 1934, 1830, 1442, 1224]

In [58]:
#add each one twice, you could also use pop() aswell to do it 
for i in lines:
    for j in temp:
        if((i+j) == 2020):
            print(str(i) +' and '+ str(j))

1165 and 855
855 and 1165

In [41]:
#they need the product of two
print(855*1165)

996075

# Part 2
<p>Using the above example again, the three entries that sum to 2020 are 979, 366, and 675. Multiplying them together produces the answer, 241861950.

In your expense report, what is the product of the three entries that sum to 2020?</p>

In [65]:
temp2 = lines.copy()

In [66]:
#we can use the same method and add a third for loop 
#not effiect way 
for i in lines:
    for j in temp:
        for k in temp2: 
            if((i+j+k) == 2020):
                print(str(i) +' + '+ str(j)+' + '+ str(k))
                break

168 + 185 + 1667
168 + 1667 + 185
185 + 168 + 1667
185 + 1667 + 168
1667 + 168 + 185
1667 + 185 + 168

what is the product of the three entries that sum to 2020?

In [68]:
print(1667*185*168)

51810360